version: '3.9'
services:
  yayois-agent:
    build:
      context: .
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /tmp/tapp-ramdisk:/tmp/tapp-ramdisk
    ports:
      - "8080:8080"
    environment:
      - DSTACK_TAPPD_ENDPOINT=/var/run/tappd.sock
      - ETHEREUM_RPC_URL=https://rpc.ankr.com/eth_sepolia
      - FACTORY_ADDRESS=0x0000000000000000000000000000000000000000
      - SECURE_FILE=/tmp/tapp-ramdisk/secure.json
      - OPENAI_API_KEY=test
      - OPENAI_MODEL=dall-e-3
      - PINATA_JWT_KEY=test
      - API_IP_PORT=0.0.0.0:8080
      - DEBUG_PLAIN_SETUP=true
      - DEBUG_SHOW_SETUP=true